export const GET_USER = 'GET_USER'
export const GET_USERS = 'GET_USERS'
export const GET_EMPLOYEE = 'GET_EMPLOYEE'
export const GET_EMPLOYEES = 'GET_EMPLOYEES'
export const GET_USER_LOGIN = 'GET_USER_LOGIN'
